name: Build GameServer Only

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Create Fake StructParser
      run: |
        mkdir Utilities\bin -Force
        echo. > Utilities\bin\StructParser.exe

    - name: Build GameServer
      shell: cmd
      run: msbuild CoreGameServer.sln /t:CoreGameServer /p:Configuration=Debug /p:Platform=Win32 /p:PreBuildEvent="" /m /v:minimal

    - name: Upload GameServer.exe
      uses: actions/upload-artifact@v4
      with:
        name: GameServer
        path: Core/bin/Debug/GameServer.exe
        if-no-files-found: error
